import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import {AppProvider} from "../components/AppContext";
import {Toaster} from "react-hot-toast";


const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500','700'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={"scroll-smooth"}>
      <body className={roboto.className} suppressHydrationWarning={true}>
      <main className={"max-w-6xl mx-auto border px-4"}>
          <AppProvider>
              <Toaster/>
          <Header/>
          {children}

          <footer className={"border-t p-8 text-gray-500 mt-10"}>
              &copy; 2024 all rights reserved
          </footer>
          </AppProvider>

      </main>


      </body>
    </html>
  );
}
